// Wraps each .glb in proto3d/models as an ES module (base64 default export),
// so the prototype also runs where .glb files can't be served (artifacts).
//   node tools/embed-glb.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

const dir = new URL('../proto3d/models/', import.meta.url);
for (const f of readdirSync(dir).filter(n => n.endsWith('.glb'))) {
  const b64 = readFileSync(new URL(f, dir)).toString('base64');
  writeFileSync(new URL(`${f}.js`, dir), `// ${f} embedded as base64 (generated by tools/embed-glb.mjs).\nexport default "${b64}";\n`);
  console.log(`${f}.js`);
}
